version: "3.8"

services:
  registry:
    image: registry:2
    container_name: registry
    ports:
      - "5000:5000"
    environment:
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
    volumes:
      - ./data/registry:/var/lib/registry
      - ./auth:/auth
    networks:
      - registry_net

  spring:
    build:
      context: .
    container_name: image-service-api
    ports:
      - "8080:8080"
    depends_on:
      - registry
    networks:
      - registry_net

networks:
  registry_net:
    driver: bridge