spring:
  datasource:
    url: jdbc:mysql://localhost:3306/registry?useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        highlight_sql: true
        default_batch_fetch_size: 1000 #최적화 옵션
    open-in-view: false #OSIV 를 true로 설정하면, request가 반환될 때 까지 커넥션을 보유
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

docker:
  registry:
    url: http://localhost:5000/v2/
logging.level:
  org.hibernate.SQL: debug # 이거 끄면 format_sql 적용 안됨
#  org.hibernate.type: trace