spring:
  datasource:
    url: jdbc:h2:mem:registry;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        highlight_sql: true
        default_batch_fetch_size: 1000 #최적화 옵션
    open-in-view: false #OSIV 를 true로 설정하면, request가 반환될 때 까지 커넥션을 보유
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

docker:
  registry:
    url: http://registry:5000/v2/
logging.level:
  org.hibernate.SQL: debug # 이거 끄면 format_sql 적용 안됨
#  org.hibernate.type: trace